const khmerAddresses = [
    "Phnom Penh, Daun Penh",
    "Phnom Penh, Chamkarmon",
    "Phnom Penh, Toul Kork",
    "Phnom Penh, Dangkao",
    "Phnom Penh, Mean Chey",
    "Phnom Penh, Russey Keo",
    "Phnom Penh, Sen Sok",
    "Phnom Penh, Prampir Makara",
    "Phnom Penh, Tuol Svay Prey",
    "Phnom Penh, Chbar Ampov",
    "Phnom Penh, Por Sen Chey",
    "Phnom Penh, Chroy Changvar",
    "Phnom Penh, Russei Keo",
    "Phnom Penh, Boeng Keng Kang",
    "Phnom Penh, Srah Chak",
    "Phnom Penh, Doun Penh",
    "Phnom Penh, Boeung Keng Kang",
    "Phnom Penh, Toul Tum Poung",
    "Phnom Penh, Sra Nge",
    "Phnom Penh, Teuk Laak 1",
    "Phnom Penh, Teuk Laak 2",
    "Phnom Penh, Teuk Thla",
    "Phnom Penh, Boeung Prolit",
    "Phnom Penh, Boeung Trabek",
    "Phnom Penh, Tonle Bassac",
    "Phnom Penh, Phsar Chas",
    "Phnom Penh, Phsar Kandal",
    "Phnom Penh, Phsar Thmei",
    "Phnom Penh, Prey Sar",
    "Phnom Penh, Prey Veng",
    "Phnom Penh, Ruessei Keo",
    "Phnom Penh, Samraong Kraom",
    "Phnom Penh, Boeng Salang",
    "Phnom Penh, Boeng Tompun",
    "Phnom Penh, Chak Angrae Leu",
    "Phnom Penh, Chak Angrae Kraom",
    "Phnom Penh, Chbar Ampov",
    "Phnom Penh, Chaom Chao",
    "Phnom Penh, Chey Chumneah",
    "Phnom Penh, Chraoy Changva",
    "Phnom Penh, Dangkao",
    "Phnom Penh, Dei Eth",
    "Phnom Penh, Nirouth",
    "Phnom Penh, Preaek Lieb",
    "Phnom Penh, Preaek Pra",
    "Phnom Penh, Preaek Thmei",
    "Phnom Penh, Preaek Thmey",
    "Phnom Penh, Preaek Aeng",
    "Phnom Penh, Preaek Kambot",
    "Phnom Penh, Preaek Leab",
    "Phnom Penh, Preaek Phnov",
    "Phnom Penh, Preaek Russey",
    "Phnom Penh, Preaek Thloeng",
    "Phnom Penh, Preaek Tapov",
    "Phnom Penh, Preaek Tasek",
    "Phnom Penh, Preaek Thmei",
    "Phnom Penh, Preaek Aeng",
    "Phnom Penh, Preaek V",
    "Phnom Penh, Prey Sa",
    "Phnom Penh, Prey Sa",
    "Phnom Penh, Prey Sar",
    "Phnom Penh, Prey Topeang",
    "Phnom Penh, Prey Veng",
    "Phnom Penh, Prum Bey",
    "Phnom Penh, Punnhea Krek",
    "Phnom Penh, Pursat",
    "Phnom Penh, Roka Kaoh",
    "Phnom Penh, Roluos",
    "Phnom Penh, Rong Chak",
    "Phnom Penh, Rong Chak",
    "Phnom Penh, Rong Krang",
    "Phnom Penh, Rong Roeurng",
    "Phnom Penh, Russey Keo",
    "Phnom Penh, Russey Sanh",
    "Phnom Penh, Russey Sen",
    "Phnom Penh, Russey Srok",
    "Phnom Penh, Ruessei Kraom",
    "Phnom Penh, Ruessei Srok",
    "Phnom Penh, Saen Sokh",
    "Phnom Penh, Samraong",
    "Phnom Penh, Samraong Kandal",
    "Phnom Penh, Samraong Tong",
    "Phnom Penh, Samraong Toul",
    "Phnom Penh, Santhor Muk",


    "Siem Reap, Siem Reap City",
    "Siem Reap, Angkor Thom",
    "Siem Reap, Angkor Wat",
    "Siem Reap, Banteay Srei",
    "Siem Reap, Banteay Samre",
    "Siem Reap, Roluos",
    "Siem Reap, Tonle Sap",
    "Siem Reap, Chong Kneas",
    "Siem Reap, Phnom Kulen",
    "Siem Reap, Preah Khan",
    "Siem Reap, Ta Prohm",
    "Siem Reap, Bayon",


    "Kampong Cham, Kampong Cham City",
    "Kampong Cham, Batheay",
    "Kampong Cham, Chamkar Leu",
    "Kampong Cham, Kang Meas",
    "Kampong Cham, Koh Sotin",
    "Kampong Cham, Prey Chhor",
    "Kampong Cham, Stueng Trang",
    "Kampong Cham, Veal Veng",
    "Kampong Cham, Cheung Prey",
    "Kampong Cham, Tbong Khmum",
    "Kampong Cham, Memot",
    "Kampong Cham, Ou Reang Ov",
    "Kampong Cham, Ponhea Kraek",
    "Kampong Cham, Kampong Siem",
    "Kampong Cham, Chikreng",
    "Kampong Cham, Snoul",
    "Kampong Cham, Kroch Chhmar",
    "Kampong Cham, Chamkar Leu",
    "Kampong Cham, Kampong Cham Thmey",
    "Kampong Cham, Memot",
    "Kampong Cham, Prey Chhor",
    "Kampong Cham, Srei Santhor",
    "Kampong Cham, Stueng Trang",

    
    "Battambang, Battambang City",
    "Battambang, Banan",
    "Battambang, Ek Phnom",
    "Battambang, Kors Kralor",
    "Battambang, Moung Ruessei",
    "Battambang, Ou Ta Ki",
    "Battambang, Rotanak Mondol",
    "Battambang, Samlout",
    "Battambang, Sangkae",
    "Battambang, Thma Koul",
    "Battambang, Bavel",
    "Battambang, Phnum Proek",
    "Battambang, Sdao",
    "Battambang, Ta Kream",
    "Battambang, Wat Kor",
    "Battambang, Wat Kor",
    "Battambang, Phnum Proek",
];

module.exports = {khmerAddresses};
  